### ISSUE TITLE
CUDA MNIST example is missing

### ISSUE THREAD

**Issue by Atcold** [torchnet/torchnet#11]
On the paper, there is also an example about how to run on GPU.
Maybe it would be worth it including it in the `example` folder.

About this example, I'm not very sure why you perform a `resize()` on the `torch.CudaTensor()` on each `onSample`. Isn't this `resize()` necessary only once?

**Comment by lvdmaaten** [comment]
Okay, I will add this.

**Comment by Atcold** [comment]
@lvdmaaten: could you please also address my question about `resize()`?

**Comment by lvdmaaten** [comment]
The `resize()` is not being called on the data itself, but on the GPU buffer the data is being copied into.

Copying data via `:cuda()` is inefficient because it does a malloc and a free each time you do it, and free is a blocking operation in CUDA. When your repeatedly copy data of the same size to the GPU, it is does much more efficient to pre-allocate a buffer on the GPU, and copy the data into that buffer. This is what the code is doing. However, the `onSample` function doesn't know for sure that the data always has the same size (for instance, the last batch of data may be smaller). To make sure we don't end up writing to memory we may not write to or end up with uninitialized memory, we do a `resize()` on the buffer to make sure it has the right size. When the buffer already had the right size (which is the case nearly always), the `resize()` doesn't do anything (it also doesn't cost anything). This way, we get the benefits of being dynamic whilst also be non-blocking nearly always.

**Comment by Atcold** [comment]
Oh, OK, I wasn't aware that `resize()` was transparent in case of already correct dimensionality.

**Comment by lvdmaaten** [comment]
https://github.com/torchnet/torchnet/commit/f3b82e86673f0fe7095711c3a78c3fcac9b8a38a
