### ISSUE TITLE
Why the software history was not kept?

### ISSUE THREAD

**Issue by gustavopinto** [torchnet/torchnet#28]
Hi there,

I'm a researcher studying software evolution. As part of my current research, I'm studying the implications of open-sourcing a proprietary software, for instance, if the project succeed in attracting newcomers. However, I observed that some projects, like _torchnet_, deleted their software history.

https://github.com/torchnet/torchnet/commit/9b7759d63ff360ba5b08b4083602f36802679c76

Knowing that software history is indispensable for developers (e.g., developers need to refer to history several times a day), I would like to ask torchnet developers the following four brief questions:

1. Why did you decide to not keep the software history?
2. Do the core developers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
3. Do the newcomers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
4. How does the lack of history impacted on software evolution? Does it placed any burden in understanding and evolving the software?

Thanks in advance for your collaboration,

Gustavo Pinto, PhD
http://www.gustavopinto.org

**Comment by gustavopinto** [comment]
hi @gforge, do you have any comments?

**Comment by gforge** [comment]
Hi Gustavo,

I developed a test suite that wasn't available in the package and the history was therefore perhaps of less importance. I was confused if they simply didn't have any tests or if they hadn't released them for the section that I was working on. As I needed the tests for my extension I did the minimum possible together with my extension, posted it in and got a verification from the main developers that the test cases were appreciated. I personally find that using the history is more useful when looking at a single file and considering a modification than an separate addition.

Regarding the evolution I did find that the engine seemed to have a different design in the past, see my [StackOverflow][so] question for details. Coming from the R-community I appreciate News-files and version numbering. This is less stringent in Torch and I do find it harder to follow without knowing how some sections have been evolved. Knowing that my question was a remnant of a previous design I can easier submit a bug fix instead of worrying that I lack some deeper understanding of the language that allows for such a construct.

I hope this helped. Good luck with your research.

Max

[so]: http://stackoverflow.com/questions/38607397/how-does-torchnets-sgdenginetrain-work-as-an-iterator

**Comment by gustavopinto** [comment]
Thank you, @gforge!

**Comment by gustavopinto** [comment]
Hi @gforge, 

thanks once again for answering our research inquiries. We were able to collect 35 responses and we drafted a research paper with the results. The paper was submitted and accepted for the 14th International Conference on Open Source Systems (http://oss2018.org/). You can find the paper [here](http://gustavopinto.org/lost+found/oss2018.pdf). Hope you enjoy reading the paper!

Thanks again,

Gustavo
