### ISSUE TITLE
OptimEngine.test not implemented

### ISSUE THREAD

**Issue by galv** [torchnet/torchnet#67]
Why is test() not implemented for the OptimEngine class? This is rather surprising to me. Seems like it should share the same functionality as SgdEngine.test(), so that that function should be used as Engine.test(), and inherited by both engines.

Happy to do this myself. Just wondering why something so necessary, e.g. for early stopping when validation error does stops going down, is missing.

**Comment by karandwivedi42** [comment]
Since OptimEngine inherits SGDEngine ([here](https://github.com/torchnet/torchnet/blob/master/engine/optimengine.lua#L46)), it uses the test function from SGDEngine.

I don't think it should be added as Engine.test() as we can write our own engines to inherit tnt.Engine, which might have different use of test function.

**Comment by galv** [comment]
Big oversight, I didn't realize that OptimEngine inherits from SGDEngine. Thanks!
