### ISSUE TITLE
fatal thread panic on parallelDatasetIterator

### ISSUE THREAD

**Issue by afgenovese** [torchnet/torchnet#69]
I get this message:

FATAL THREAD PANIC: (read) /Users/genovese/torch/install/share/lua/5.1/torch/File.lua:343: unknown Torch class <package.torchnet>

This is relevant code:
```
local tnt = require 'torchnet'

function getIterator(dataset)
    return tnt.ParallelDatasetIterator{
    init    = function() 
            tnt = require 'torchnet' 
            optParser = require 'opts'
            opt = optParser.parse(arg) end,
    nthread = opt.nThreads,
    closure = function(dataset)
            return tnt.DasetIterator{
                dataset = tnt.BatchDataset{
                    batchsize = opt.batchsize,
                    dataset = dataset
                }
            } end
        }
end
```

**Comment by lvdmaaten** [comment]
Can you try doing `require 'torchnet'` instead of `tnt = require 'torchnet'` in the `init()` function? The fact that you have two `tnt` variables around makes things tricky here: is the `tnt` in `tnt.BatchDataset` the upvalue or the global `tnt` in the thread?

Also, `closure` does not take any input arguments and should return a `Dataset`, not a `DatasetIterator`. The `dataset` variable you want to use in the `closure()` can be an upvalue, presuming it is serializable.
