### ISSUE TITLE
returning vector in ListDataset problem.

### ISSUE THREAD

**Issue by neuralix** [torchnet/torchnet#73]
in latest torchnet, i tried to run examples/mnist.lua changing criterion adopting MSECriterion.
and following the condition, i made target as vector like this,

target = torch.LongTensor(1,10) or target = torch.LongTensor(10, 1)
from
target = torch.LongTensor{dataset.label[idx] + 1}
(to just check whether it works, i didn't assign the label.)

but it's fail. 

I suspect returning vector in getIterator(mode) {...} 
(specifically, variable 'load' in ListDataset cannot contain vector as target)
does not work.

will you have a plan to repair it near some day?

**Comment by fmassa** [comment]
You need to have your target Tensor to be a 1 tensor (`target = torch.Tensor(10)`), so that when it gets concatenated it becomes a 2D tensor instead.
Also, you need to remove the `meters` that only work for classification, like the `ClassErrorMeter`.
Those are the only changes needed in the example for it to work with MSECriterion.

**Comment by neuralix** [comment]
Thank you. I checked it.
But absence of meter (and also class error meter) makes results to nonsense one.
I'll think further.
The question what it asked is closed.

**Comment by neuralix** [comment]
Thank you. I checked it.
But absence of meter (and also class error meter) makes results to nonsense one.
I'll think further.
The question what it asked is closed.
